# Generated by Django 5.1.6 on 2025-03-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descriptions...', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='titel',
            field=models.TextField(default='Title', max_length=100),
        ),
    ]
