# Generated by Django 5.1.6 on 2025-03-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_titel_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
    ]
